[package]
name = "yuki"
version = "0.1.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/crispybaccoon/yuki"
license = "MIT OR Apache-2.0"

[[bin]]
name = "yki"
path = "src/main.rs"

[dependencies]
clap = "4.4.4"
