[package]
name = "saku-lib"
version = "0.1.0"

[lib]
path = "lib.rs"

[dependencies]
directories = "5.0.1"
lazy_static = "1.4.0"
regex = "1.9.6"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
toml = "0.8.2"
